on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    name: Create Release
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          generateReleaseNotes: true
          draft: true
          prerelease: false

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yaml
          workflow_conclusion: success

      - name: Package
        run: |
          tar -c -a -f stfc-community-patch.zip -C stfc-community-patch *.dll

      - name: Upload Community Patch
        id: upload-patch
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stfc-community-patch.zip
          asset_name: stfc-community-patch.zip
          asset_content_type: application/zip

      - name: Upload Community Patch
        id: upload-patch-versioned
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stfc-community-patch.zip
          asset_name: stfc-community-patch-${{ github.ref }}.zip
          asset_content_type: application/zip
